import type {Metadata} from 'next';
import './globals.scss';
import ss from './layout.module.scss';
import Header from '@/Layout/Header/Header';
import Nav from '@/Layout/Nav/Nav';

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body>
                <div className={ss.container}>
                    <Header />
                    <div className={ss.content}>{children}</div>
                    <Nav />
                </div>
            </body>
        </html>
    );
}
